// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240625153217_[]")]
    partial class _
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Chatlieu", b =>
                {
                    b.Property<int>("IdChatlieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CHATLIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatlieu"));

                    b.Property<string>("Tenchatlieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHATLIEU");

                    b.HasKey("IdChatlieu")
                        .HasName("PK__CHATLIEU__3912AF289F0644BF");

                    b.ToTable("CHATLIEU");
                });

            modelBuilder.Entity("DAL.Models.Chucvu", b =>
                {
                    b.Property<int>("IdChucvu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CHUCVU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucvu"));

                    b.Property<string>("Tenchucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHUCVU");

                    b.HasKey("IdChucvu")
                        .HasName("PK__CHUCVU__ACDE8E29231C707F");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.Property<int>("IdHoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HOADON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoadon"));

                    b.Property<int?>("IdKhachhang")
                        .HasColumnType("int")
                        .HasColumnName("ID_KHACHHANG");

                    b.Property<string>("IdKhuyenmai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID_KHUYENMAI");

                    b.Property<DateOnly?>("NgayTao")
                        .HasColumnType("date");

                    b.Property<double?>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("IdHoadon")
                        .HasName("PK__HOADON__018FF0B57137B976");

                    b.HasIndex("IdKhachhang");

                    b.HasIndex("IdKhuyenmai");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("DAL.Models.Hoadonct", b =>
                {
                    b.Property<int>("IdHoadonct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_HOADONCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHoadonct"));

                    b.Property<double?>("Giasp")
                        .HasColumnType("float")
                        .HasColumnName("GIASP");

                    b.Property<int?>("IdHoadon")
                        .HasColumnType("int")
                        .HasColumnName("ID_HOADON");

                    b.Property<int?>("IdSanphamct")
                        .HasColumnType("int")
                        .HasColumnName("ID_SANPHAMCT");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("IdHoadonct")
                        .HasName("PK__HOADONCT__CB5C3B207A9A076B");

                    b.HasIndex("IdHoadon");

                    b.HasIndex("IdSanphamct");

                    b.ToTable("HOADONCT");
                });

            modelBuilder.Entity("DAL.Models.Khachhang", b =>
                {
                    b.Property<int>("IdKhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_KHACHHANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKhachhang"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Hovaten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOVATEN");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("IdKhachhang")
                        .HasName("PK__KHACHHAN__769C0DEB06885947");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("DAL.Models.Khuyenmai", b =>
                {
                    b.Property<string>("IdKhuyenmai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ID_KHUYENMAI");

                    b.Property<DateOnly?>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateOnly?>("Ngayhethan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYHETHAN");

                    b.Property<DateOnly?>("Ngaytao")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTAO");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal?>("Sophantramkhuyenmai")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("SOPHANTRAMKHUYENMAI");

                    b.Property<string>("Tenkhuyenmai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKHUYENMAI");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("IdKhuyenmai")
                        .HasName("PK__KHUYENMA__C2E0A21097623CEC");

                    b.ToTable("KHUYENMAI");
                });

            modelBuilder.Entity("DAL.Models.Kichthuoc", b =>
                {
                    b.Property<int>("IdKichthuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_KICHTHUOC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKichthuoc"));

                    b.Property<int?>("Size")
                        .HasColumnType("int")
                        .HasColumnName("SIZE");

                    b.HasKey("IdKichthuoc")
                        .HasName("PK__KICHTHUO__854A5CB7E88DA72D");

                    b.ToTable("KICHTHUOC");
                });

            modelBuilder.Entity("DAL.Models.Loaisanpham", b =>
                {
                    b.Property<int>("IdLoaisanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_LOAISANPHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLoaisanpham"));

                    b.Property<string>("Tenloaisanpham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAISANPHAM");

                    b.HasKey("IdLoaisanpham")
                        .HasName("PK__LOAISANP__D4D52375024DF897");

                    b.ToTable("LOAISANPHAM");
                });

            modelBuilder.Entity("DAL.Models.Mau", b =>
                {
                    b.Property<int>("IdMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MAU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMau"));

                    b.Property<string>("Tenmau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENMAU");

                    b.HasKey("IdMau")
                        .HasName("PK__MAU__276D397D5D626397");

                    b.ToTable("MAU");
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.Property<int>("IdNhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_NHANVIEN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhanvien"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hovaten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOVATEN");

                    b.Property<int?>("IdChucvu")
                        .HasColumnType("int")
                        .HasColumnName("ID_CHUCVU");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<int?>("Sdt")
                        .HasColumnType("int")
                        .HasColumnName("SDT");

                    b.HasKey("IdNhanvien")
                        .HasName("PK__NHANVIEN__DE90FCA31084BD1E");

                    b.HasIndex("IdChucvu");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.Property<int>("IdSanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SANPHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanpham"));

                    b.Property<int?>("IdThuonghieu")
                        .HasColumnType("int")
                        .HasColumnName("ID_THUONGHIEU");

                    b.Property<string>("Mota")
                        .HasColumnType("text")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tensanpham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSANPHAM");

                    b.HasKey("IdSanpham")
                        .HasName("PK__SANPHAM__216A05531AAF96E4");

                    b.HasIndex("IdThuonghieu");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("DAL.Models.Sanphamct", b =>
                {
                    b.Property<int>("IdSanphamct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SANPHAMCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSanphamct"));

                    b.Property<double?>("Dongia")
                        .HasColumnType("float")
                        .HasColumnName("DONGIA");

                    b.Property<int?>("IdChatlieu")
                        .HasColumnType("int")
                        .HasColumnName("ID_CHATLIEU");

                    b.Property<int?>("IdKichthuoc")
                        .HasColumnType("int")
                        .HasColumnName("ID_KICHTHUOC");

                    b.Property<int?>("IdLoaisanpham")
                        .HasColumnType("int")
                        .HasColumnName("ID_LOAISANPHAM");

                    b.Property<int?>("IdMau")
                        .HasColumnType("int")
                        .HasColumnName("ID_MAU");

                    b.Property<int?>("IdSanpham")
                        .HasColumnType("int")
                        .HasColumnName("ID_SANPHAM");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("IdSanphamct")
                        .HasName("PK__SANPHAMC__99B856117AD9B018");

                    b.HasIndex("IdChatlieu");

                    b.HasIndex("IdKichthuoc");

                    b.HasIndex("IdLoaisanpham");

                    b.HasIndex("IdMau");

                    b.HasIndex("IdSanpham");

                    b.ToTable("SANPHAMCT");
                });

            modelBuilder.Entity("DAL.Models.Thuonghieu", b =>
                {
                    b.Property<int>("IdThuonghieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_THUONGHIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThuonghieu"));

                    b.Property<string>("Tenthuonghieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTHUONGHIEU");

                    b.HasKey("IdThuonghieu")
                        .HasName("PK__THUONGHI__1A0670700CC3CDDC");

                    b.ToTable("THUONGHIEU");
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.HasOne("DAL.Models.Khachhang", "IdKhachhangNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("IdKhachhang")
                        .HasConstraintName("FK__HOADON__ID_KHACH__403A8C7D");

                    b.HasOne("DAL.Models.Khuyenmai", "IdKhuyenmaiNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("IdKhuyenmai")
                        .HasConstraintName("FK__HOADON__ID_KHUYE__412EB0B6");

                    b.Navigation("IdKhachhangNavigation");

                    b.Navigation("IdKhuyenmaiNavigation");
                });

            modelBuilder.Entity("DAL.Models.Hoadonct", b =>
                {
                    b.HasOne("DAL.Models.Hoadon", "IdHoadonNavigation")
                        .WithMany("Hoadoncts")
                        .HasForeignKey("IdHoadon")
                        .HasConstraintName("FK__HOADONCT__ID_HOA__5CD6CB2B");

                    b.HasOne("DAL.Models.Sanphamct", "IdSanphamctNavigation")
                        .WithMany("Hoadoncts")
                        .HasForeignKey("IdSanphamct")
                        .HasConstraintName("FK__HOADONCT__ID_SAN__5BE2A6F2");

                    b.Navigation("IdHoadonNavigation");

                    b.Navigation("IdSanphamctNavigation");
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.HasOne("DAL.Models.Chucvu", "IdChucvuNavigation")
                        .WithMany("Nhanviens")
                        .HasForeignKey("IdChucvu")
                        .HasConstraintName("FK__NHANVIEN__ID_CHU__33D4B598");

                    b.Navigation("IdChucvuNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.HasOne("DAL.Models.Thuonghieu", "IdThuonghieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("IdThuonghieu")
                        .HasConstraintName("FK__SANPHAM__ID_THUO__36B12243");

                    b.Navigation("IdThuonghieuNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sanphamct", b =>
                {
                    b.HasOne("DAL.Models.Chatlieu", "IdChatlieuNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("IdChatlieu")
                        .HasConstraintName("FK__SANPHAMCT__ID_CH__3B75D760");

                    b.HasOne("DAL.Models.Kichthuoc", "IdKichthuocNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("IdKichthuoc")
                        .HasConstraintName("FK__SANPHAMCT__ID_KI__398D8EEE");

                    b.HasOne("DAL.Models.Loaisanpham", "IdLoaisanphamNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("IdLoaisanpham")
                        .HasConstraintName("FK__SANPHAMCT__ID_LO__3D5E1FD2");

                    b.HasOne("DAL.Models.Mau", "IdMauNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("IdMau")
                        .HasConstraintName("FK__SANPHAMCT__ID_MA__3A81B327");

                    b.HasOne("DAL.Models.Sanpham", "IdSanphamNavigation")
                        .WithMany("Sanphamcts")
                        .HasForeignKey("IdSanpham")
                        .HasConstraintName("FK__SANPHAMCT__ID_SA__3C69FB99");

                    b.Navigation("IdChatlieuNavigation");

                    b.Navigation("IdKichthuocNavigation");

                    b.Navigation("IdLoaisanphamNavigation");

                    b.Navigation("IdMauNavigation");

                    b.Navigation("IdSanphamNavigation");
                });

            modelBuilder.Entity("DAL.Models.Chatlieu", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("DAL.Models.Chucvu", b =>
                {
                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.Navigation("Hoadoncts");
                });

            modelBuilder.Entity("DAL.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Khuyenmai", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Kichthuoc", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("DAL.Models.Loaisanpham", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("DAL.Models.Mau", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.Navigation("Sanphamcts");
                });

            modelBuilder.Entity("DAL.Models.Sanphamct", b =>
                {
                    b.Navigation("Hoadoncts");
                });

            modelBuilder.Entity("DAL.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
